version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nes_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: nes_eventos
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: